name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Create runtime-config.js
        run: |
          echo "(function(window) { window.__env = window.__env || {}; window.__env.admin = '${{ vars.Admin }}'; window.__env.developer = '${{ vars.Developer }}'; }(this));" > src/runtime-config.js

      - name: Build Angular project
        run: npm run build -- --prod
