name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Echo environment variables
        run: |
          echo "Admin is ${{ vars.Admin }}"
          echo "Developer is ${{ vars.Developer }}"

      - name: Build Angular project
        run: npm run build --prod
        env:
          Admin: ${{ vars.Admin }}
          Developer: ${{ vars.Developer }}
